import React from "react";
import type { Metadata } from "next";
import { PolicyLayout } from "@/components/policy/PolicyLayout";
import { CONTACT_CONFIG } from "@/lib/contact-config";

export const metadata: Metadata = {
  title: "Privacy Policy | NEKARA",
  description:
    "Learn how NEKARA collects, secures, and respects your personal data in accordance with modern privacy standards.",
};

export default function PrivacyPolicyPage() {
  return (
    <PolicyLayout
      title="Privacy Policy"
      subtitle="Official Privacy Policy"
      currentPath="/privacy"
      intro="NEKARA is committed to protecting your privacy and treating your personal data with utmost discretion and dignity. This Privacy Policy details the types of personal data we collect when you visit our website, how we utilize and safeguard that data, and your rights concerning your personal information."
    >
      <div className="space-y-10 text-[#2C2C2C] font-serif leading-relaxed">
        {/* Section 1 */}
        <section className="space-y-4">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            1. Information We Collect
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            To provide a bespoke luxury shopping experience, we may collect the following categories of information:
          </p>
          <ul className="list-disc list-outside pl-5 space-y-2 text-sm sm:text-base text-[#2C2C2C]/85 font-sans">
            <li>
              <strong>Identity &amp; Contact Details:</strong> Full name, shipping and billing addresses, email address, mobile phone number, and postal code.
            </li>
            <li>
              <strong>Account &amp; Profile Data:</strong> Firebase Authentication identifiers, saved delivery addresses, wishlist selections, and order history.
            </li>
            <li>
              <strong>Transaction &amp; Order Data:</strong> Details of items purchased, order totals, timestamp, fulfillment progress, and payment identifiers generated by our gateway partner (Razorpay). <em>Note: NEKARA never stores your credit card numbers, CVV codes, or net-banking credentials.</em>
            </li>
            <li>
              <strong>Technical &amp; Usage Data:</strong> Internet protocol (IP) address, browser type and version, device operating system, referral URL, and browsing interactions.
            </li>
          </ul>
        </section>

        {/* Section 2 */}
        <section className="space-y-4 pt-4 border-t border-[#B58A45]/20">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            2. How We Use Your Information
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            We use your personal data solely for legitimate business purposes, including:
          </p>
          <ul className="list-disc list-outside pl-5 space-y-2 text-sm sm:text-base text-[#2C2C2C]/85 font-sans">
            <li>Processing, packing, verifying, and dispatching your saree orders to your designated address.</li>
            <li>Sending critical transactional notifications (order confirmation, tracking updates, invoice receipts, refund confirmations).</li>
            <li>Delivering personalized concierge customer care via WhatsApp and email.</li>
            <li>Maintaining the security and integrity of our digital infrastructure, preventing fraudulent transactions, and complying with statutory tax obligations.</li>
            <li>Sending occasional curated lookbooks and new collection announcements, provided you have opted in (you may unsubscribe at any time).</li>
          </ul>
        </section>

        {/* Section 3 */}
        <section className="space-y-4 pt-4 border-t border-[#B58A45]/20">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            3. Third-Party Service Providers
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            We do not sell, rent, or lease your personal information to third-party marketers. We share minimal necessary data only with trusted infrastructure partners bound by strict data confidentiality agreements:
          </p>
          <ul className="list-disc list-outside pl-5 space-y-2 text-sm sm:text-base text-[#2C2C2C]/85 font-sans">
            <li>
              <strong>Payment Gateway:</strong> Razorpay Software Private Limited for encrypted, PCI-DSS compliant payment processing.
            </li>
            <li>
              <strong>Cloud &amp; Database:</strong> Google Cloud Platform / Firebase for secure, ISO-27001 compliant database and authentication infrastructure.
            </li>
            <li>
              <strong>Logistics &amp; Courier Partners:</strong> Premium express couriers (e.g. Blue Dart, Delhivery) strictly for the physical delivery of your parcels.
            </li>
            <li>
              <strong>Image &amp; Asset Delivery:</strong> Cloudinary and Vercel for high-speed edge distribution and content serving.
            </li>
          </ul>
        </section>

        {/* Section 4 */}
        <section className="space-y-4 pt-4 border-t border-[#B58A45]/20">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            4. Cookies &amp; Tracking Technologies
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            Our website uses essential session cookies to remember your cart items, authentication session, and display preferences. We also use aggregated analytical cookies to understand how visitors engage with our store, enabling us to optimize navigation and loading speeds. You may configure your browser to decline cookies, though certain interactive features of our store may be impaired.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-4 pt-4 border-t border-[#B58A45]/20">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            5. Data Security &amp; Retention
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            We implement industry-standard encryption (TLS/SSL) for all data in transit and robust Firestore security rules restricting unauthorized database access. While no internet transmission is 100% impenetrable, we rigorously monitor our systems to safeguard your records.
          </p>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            We retain your order and transactional data for as long as required to service your account, fulfill warranty or exchange requests, and comply with Indian statutory accounting and tax retention regulations.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-4 pt-4 border-t border-[#B58A45]/20">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            6. Your Privacy Rights
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            You have the right to request access to the personal information we hold about you, request corrections to erroneous address records, or ask for the deletion of your customer account, subject to statutory tax retention requirements. To exercise any of these rights, contact us at{" "}
            {CONTACT_CONFIG.isRealEmailConfigured() ? (
              <a
                href={CONTACT_CONFIG.getMailtoHref("Privacy Data Request")!}
                className="font-medium text-[#1C3F3A] underline hover:text-[#B58A45] transition-colors"
              >
                {CONTACT_CONFIG.supportEmail}
              </a>
            ) : (
              <span className="font-mono text-xs bg-amber-50 px-2 py-0.5 rounded-sm border border-amber-200 text-amber-800">
                {CONTACT_CONFIG.supportEmail}
              </span>
            )}
            .
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-4 pt-4 border-t border-[#B58A45]/20">
          <h2 className="font-serif text-xl sm:text-2xl text-[#1C3F3A] font-semibold tracking-wide">
            7. Contact our Privacy Officer
          </h2>
          <p className="text-sm sm:text-base leading-relaxed text-[#2C2C2C]/90 font-sans">
            For inquiries, clarification, or feedback concerning our privacy policies, please reach out via email to{" "}
            {CONTACT_CONFIG.isRealEmailConfigured() ? (
              <a
                href={CONTACT_CONFIG.getMailtoHref("Privacy Inquiry")!}
                className="font-medium text-[#1C3F3A] underline hover:text-[#B58A45] transition-colors"
              >
                {CONTACT_CONFIG.supportEmail}
              </a>
            ) : (
              <span className="font-mono text-xs bg-amber-50 px-2 py-0.5 rounded-sm border border-amber-200 text-amber-800">
                {CONTACT_CONFIG.supportEmail}
              </span>
            )}{" "}
            or via our WhatsApp Concierge at{" "}
            {CONTACT_CONFIG.isRealWhatsAppConfigured() ? (
              <a
                href={CONTACT_CONFIG.getWhatsAppHref("Hello NEKARA Privacy Officer, I have an inquiry.")!}
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-[#1C3F3A] underline hover:text-[#B58A45] transition-colors"
              >
                {CONTACT_CONFIG.whatsappNumber}
              </a>
            ) : (
              <span className="font-mono text-xs bg-amber-50 px-2 py-0.5 rounded-sm border border-amber-200 text-amber-800">
                {CONTACT_CONFIG.whatsappNumber}
              </span>
            )}
            .
          </p>
        </section>
      </div>
    </PolicyLayout>
  );
}
